einden_ephoto_attribute_index:
    path: /attribute
    defaults: { _controller: EindenEphotoConnectorBundle:Rest:attributeIndex}
    methods: [GET]
einden_ephoto_attribute_show_by_id:
    path: /attribute/{id}
    requirements:
        id: '\d+'
    defaults: { _controller: EindenEphotoConnectorBundle:Rest:attributeDetail}
    methods: [GET]
einden_ephoto_attribute_show_by_code:
    path: /attribute/{code}
    defaults: { _controller: EindenEphotoConnectorBundle:Rest:attributeDetailByCode}
    methods: [GET]
