css:
    eindenephotoconnector:
        - bundles/eindenephotoconnector/css/ephoto-configuration.css
        - bundles/eindenephotoconnector/css/ephoto-field.css
        - bundles/eindenephotoconnector/css/ephoto-datagrid.css
