css:
    eindenephotoconnector:
        - bundles/eindenephotoconnector/css/configuration.css
        #- bundles/eindenephotoconnector/css/asset-gallery.css
        #- bundles/eikonatessaconnector/css/datagrid.less