extensions:
    einden-ephoto-asset-selection-form:
        module: einden/ephoto/connector/mam-asset-selection-form
        targetZone: self
    einden-ephoto-system-configuration:
        module: einden/ephoto/connector/system/configuration
        parent: oro-system-config-system
        targetZone: content
        position: 120
    einden-ephoto-product-edit-form-product-info:
        module: einden/ephoto/connector/attributes/product-info
        parent: pim-product-edit-form-attributes
        targetZone: self
        position: 100
attribute_fields:
    einden-ephoto-field: einden/ephoto/connector/einden-mam-field