#parameters:
#    pim_datagrid.extension.formatter.property.product_value.field_property.class: Einden\Ephoto\ConnectorBundle\DataGrid\Extension\Formatter\Property\ProductValue\FieldProperty


services:
    einden.ephoto.datagrid.extension.formatter.property.product_value.einden_catalog_ephoto:
        class: Einden\Ephoto\ConnectorBundle\DataGrid\Formatter\Property\ProductValue\EphotoProperty
        arguments:
            - '@twig'
            - '@translator'
            - '@einden.ephoto'
        tags:
            - { name: oro_datagrid.extension.formatter.property, type: product_value_ephoto }
