config:
    paths:
        einden/ephoto/connector/field-ephoto:                eindenephotoconnector/js/product/field/ephoto-field
        einden/ephoto/connector/system/configuration:               eindenephotoconnector/js/form/system
        einden/ephoto/connector/attributes/product-info:            eindenephotoconnector/js/product/form/attributes/product-info
