services:
    einden.ephoto.connector.provider.field.mam:
        class: Einden\Ephoto\ConnectorBundle\Enrich\Provider\Field\MamFieldProvider
        tags:
            - { name: pim_enrich.provider.field, priority: 90 }
