parameters:
    einden.ephoto.connector.provider.field.mam.class: Einden\Ephoto\ConnectorBundle\Enrich\Provider\Field\MamFieldProvider


services:
    einden.ephoto:
        class: 'Einden\Ephoto\ConnectorBundle\Ephoto'
        arguments:
            - '@oro_config.global'
            - '@router'
            - '@pim_serializer'
            - '@kernel'
            - '@logger'
    #einden.utilities.math:
    #    class: Einden\Ephoto\ConnectorBundle\Utilities\Math
    einden.ephoto.connector.provider.field.mam:
        class: %einden.ephoto.connector.provider.field.mam.class%
        tags:
            - { name: pim_enrich.provider.field, priority: 90 }
    #einden.ephoto.auth_guard:
    #    class: 'Einden\Ephoto\ConnectorBundle\Security\AuthGuard'
    #    arguments:
    #        - '@einden.ephoto'
    #        - '@einden.utilities.math'
    #        - '@logger'

    #einden.ephoto.serializer.normalizer.product:
    #    class: Einden\Ephoto\ConnectorBundle\Extension\Normalizer\Standard\ProductNormalizer
    #    arguments:
    #        - '@einden.ephoto.serializer.normalizer.product_properties'
    #        - '@pim_catalog.normalizer.standard.product.associations'
    #        - '@request_stack'
    #    tags:
    #        - { name: pim_serializer.normalizer, priority: 91 }
    #einden.ephoto.serializer.normalizer.attribute:
    #    class: Einden\Ephoto\ConnectorBundle\Extension\Normalizer\Standard\AttributeNormalizer
    #    arguments:
    #        - '@pim_catalog.normalizer.standard.translation'
    #        - '@pim_catalog.normalizer.standard.datetime'
    #        - '@request_stack'
    #    tags:
    #        - { name: pim_serializer.normalizer, priority: 91 }


    #einden.ephoto.serializer.normalizer.product_properties:
    #    class: Einden\Ephoto\ConnectorBundle\Extension\Normalizer\Standard\ProductPropertiesNormalizer
    #    arguments:
    #        - '@pim_catalog.filter.chained'
    #        - '@request_stack'
    #    tags:
    #        - { name: pim_serializer.normalizer, priority: 91 }
    #einden.ephoto.serializer.normalizer.channel:
    #    class: Einden\Ephoto\ConnectorBundle\Extension\Normalizer\Standard\ChannelNormalizer
    #    parent: pim_catalog.normalizer.standard.channel
    #    arguments:
    #        - '@request_stack'
    #    tags:
    #        - { name: pim_serializer.normalizer, priority: 91 }

    #einden.ephoto.serializer.normalizer.category:
    #    class: Einden\Ephoto\ConnectorBundle\Extension\Normalizer\Standard\CategoryNormalizer
    #    arguments:
    #        - '@pim_catalog.normalizer.standard.translation'
    #        - '@request_stack'
    #    tags:
    #        - { name: pim_serializer.normalizer, priority: 91 }
